# cloudbuild.yaml - Configuración para Google Cloud Build
# Este archivo le dice a Cloud Build que use el Dockerfile explícitamente
#
# IMPORTANTE: Las variables NEXT_PUBLIC_* deben pasarse como substitutions durante el build
# Ejemplo de uso:
#   gcloud builds submit --config cloudbuild.yaml \
#     --substitutions=_NEXT_PUBLIC_SUPABASE_URL=https://xxx.supabase.co,_NEXT_PUBLIC_SUPABASE_ANON_KEY=xxx,_NEXT_PUBLIC_BUNNY_CDN_URL=https://xxx.b-cdn.net

steps:
  # Construir la imagen usando el Dockerfile con build args para variables NEXT_PUBLIC_*
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/decks-imperio:latest'
      - '-f'
      - 'Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_BUNNY_CDN_URL=${_NEXT_PUBLIC_BUNNY_CDN_URL}'
      - '.'
  
  # Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/decks-imperio:latest']

images:
  - 'gcr.io/$PROJECT_ID/decks-imperio:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Substitutions por defecto (pueden ser sobrescritas al ejecutar gcloud builds submit)
substitutions:
  _NEXT_PUBLIC_SUPABASE_URL: ''
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: ''
  _NEXT_PUBLIC_BUNNY_CDN_URL: ''

